enum RideStatus {
  INITIAL_MAP,
  RIDE_TYPE_BOTTOM_SHEET_SHOWING,
  VEHICLE_TYPE_BOTTOM_SHEET_SHOWING,
  RIDE_DETAILS_BOTTOM_SHEET_SHOWING,
  RIDE_NEGOTIATION_BOTTOM_SHEET_SHOWING,
  RIDE_NEGOTIATION_BOTTOM_SHEET_SHOWING_FOR_COMMENT,
  DRIVER_SEARCHING,
  DRIVER_BID_ARRIVED,
  RIDE_CONFIRMATION_PIN_BOTTOM_SHEET_SHOWING,
  RIDE_IN_PROGRESS,
  WANT_TO_CANCEL_RIDE,
  WANT_TO_CANCEL_RIDE_AFTER_DRIVER_ACCEPT,
  REASON_TO_CANCEL_RIDE,
  RIDE_COMPLETED
}
